### ISSUE TITLE
Error: object 'annotatePeptideSequences' not found

### ISSUE THREAD

**Issue by ling-t** [ibludau/ProteoformAnanlysis#1]
dear,
When I load the CCprofile package and use the annotatePeptideSequences function, I get an Error: object'annotatePeptideSequences' not found. I don't know why. 

Thanks

**Comment by ibludau** [comment]
The proteoform functions are currently not available from the master branch.
You need to switch to the 'proteoformLocationMapping' branch to have all functions available.  
You can for example install the package like this:

library(devtools)
install_github("CCprofiler/CCprofiler", ref =  "proteoformLocationMapping")

Please let me know if this works for you. 
Best,
Isabell

**Comment by ling-t** [comment]
The dependent package ‘maps’ needs to be configured manually, but I don’t know how to solve it. 

*** arch - i386
Warning: replacing previous import 'GenomicRanges::shift' by 'data.table::shift' when loading 'CCprofiler'
Error: package or namespace load failed for 'CCprofiler' in library.dynam(lib, package, package.lib):
 DLL 'maps' not found: maybe not installed for this architecture?
*** arch - x64
Warning: replacing previous import 'GenomicRanges::shift' by 'data.table::shift' when loading 'CCprofiler'
ERROR: loading failed for 'i386'
* removing 'F:/R/R-3.6.3/library/CCprofiler'
* restoring previous 'F:/R/R-3.6.3/library/CCprofiler'

Thanks,
Ling

**Comment by ling-t** [comment]
Thank you, the problem is solved, and finally the package can be installed using this command line " install_github("CCprofiler/CCprofiler", ref = "proteoformLocationMapping",INSTALL_opts = c("--no-multiarch")) " 

Thanks,
Ling

**Comment by ibludau** [comment]
Dear Ling,
Thanks for letting me know - I'm glad to hear that!
Please let me know in case you encounter any additional difficulties.
Best,
Isabell
